import colors from "tailwindcss/colors";

export const Colors = {
  light: {
    text: colors.zinc[900],
    textInverse: colors.zinc[100],
    textMuted: colors.zinc[500],
    background: colors.zinc[50],
    backgroundModal: colors.zinc[200],
    backgroundModalHeader: colors.zinc[300],
    border: colors.zinc[400],
    tabIconSelected: colors.zinc[200],
    headerBackground: colors.zinc[300],
    headerForeground: colors.zinc[700],
    tabBarForeground: colors.zinc[700],
    buttonBackground: colors.zinc[900],
    buttonForeground: colors.zinc[200],
    buttonSecondaryBackground: colors.zinc[200],
    buttonSecondaryForeground: colors.zinc[900],
    inputBorder: colors.zinc[200],
    inputBackground: colors.zinc[100],
    inputForeground: colors.zinc[600],
    accent: colors.sky[500],
  },
  dark: {
    text: colors.zinc[100],
    textInverse: colors.zinc[900],
    textMuted: colors.zinc[400],
    background: colors.zinc[800],
    backgroundModal: colors.zinc[600],
    backgroundModalHeader: colors.zinc[700],
    border: colors.zinc[900],
    tabIconSelected: colors.zinc[800],
    headerBackground: colors.zinc[900],
    headerForeground: colors.zinc[200],
    tabBarForeground: colors.zinc[200],
    buttonBackground: colors.zinc[200],
    buttonForeground: colors.zinc[900],
    buttonSecondaryBackground: colors.zinc[900],
    buttonSecondaryForeground: colors.zinc[200],
    inputBorder: colors.zinc[600],
    inputBackground: colors.zinc[900],
    inputForeground: colors.zinc[200],
    accent: colors.sky[400],
  },
};
