# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^backend/migrations/.*
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: ts-lint-fix
        name: TypeScript Lint Fix
        entry: bash -c 'if [[ "$FILE" =~ ^frontend/ ]]; then cd frontend && pnpm lint:fix; elif [[ "$FILE" =~ ^mobile/ ]]; then cd mobile && pnpm lint:fix; elif [[ "$FILE" =~ ^firebase/ ]]; then cd firebase && pnpm lint:fix; fi'
        language: system
        files: ^(frontend|mobile|firebase)/.*\.(ts|tsx)$
        pass_filenames: true
        always_run: false
      - id: ts-format
        name: TypeScript Format
        entry: bash -c 'if [[ "$FILE" =~ ^frontend/ ]]; then cd frontend && pnpm format; elif [[ "$FILE" =~ ^mobile/ ]]; then cd mobile && pnpm format; elif [[ "$FILE" =~ ^firebase/ ]]; then cd firebase && pnpm format; fi'
        language: system
        files: ^(frontend|mobile|firebase)/.*\.(ts|tsx)$
        pass_filenames: true
        always_run: false
      - id: ts-test
        name: TypeScript Tests
        entry: bash -c 'if [[ "$FILE" =~ ^frontend/ ]]; then cd frontend && pnpm test; elif [[ "$FILE" =~ ^mobile/ ]]; then cd mobile && pnpm test; fi'
        language: system
        files: ^(frontend|mobile)/.*\.(ts|tsx)$
        pass_filenames: true
        always_run: false
