networks:
  exchange-house-network:
    name: exchange-house-network
  external_proxy_net:
    external: true
    name: proxy_net

services:
  exchange-house:
    container_name: exchange-house
    image: ghcr.io/jszymanowski/exchange-house:latest
    environment:
      - ENV=production
      - WORKERS=4
      # TODO: move these to secrets
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-exchange_house_production}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    ports:
      - "3177:8000"
    networks:
      - exchange-house-network
      - external_proxy_net
    depends_on:
      - postgres

  postgres:
    container_name: exchange-house-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-exchange-house-production}
    volumes:
      - ${POSTGRES_DATA_PATH:-/mnt/cache/appdata/exchange-house-postgres}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - exchange-house-network
    restart: unless-stopped
