export type CurrencyCode = (typeof CURRENCY_SYMBOLS)[number];

interface Currency {
  symbol: string;
  name: string;
  icon: string;
}

export const CURRENCIES: Record<CurrencyCode, Currency> = {
  AED: {
    symbol: "د.إ",
    name: "United Arab Emirates Dirham",
    icon: "🇦🇪",
  },
  AFN: {
    symbol: "؋",
    name: "Afghan Afghani",
    icon: "🇦🇫",
  },
  ALL: {
    symbol: "L",
    name: "Albanian Lek",
    icon: "🇦🇱",
  },
  AMD: {
    symbol: "֏",
    name: "Armenian Dram",
    icon: "🇦🇲",
  },
  ANG: {
    symbol: "ƒ",
    name: "Netherlands Antillean Guilder",
    icon: "🇸🇽",
  },
  AOA: {
    symbol: "Kz",
    name: "Angolan Kwanza",
    icon: "🇦🇴",
  },
  ARS: {
    symbol: "$",
    name: "Argentine Peso",
    icon: "🇦🇷",
  },
  AUD: {
    symbol: "$",
    name: "Australian Dollar",
    icon: "🇹🇻",
  },
  AWG: {
    symbol: "ƒ",
    name: "Aruban Florin",
    icon: "🇦🇼",
  },
  AZN: {
    symbol: "₼",
    name: "Azerbaijani Manat",
    icon: "🇦🇿",
  },
  BAM: {
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    icon: "🇧🇦",
  },
  BBD: {
    symbol: "$",
    name: "Barbadian Dollar",
    icon: "🇧🇧",
  },
  BDT: {
    symbol: "৳",
    name: "Bangladeshi Taka",
    icon: "🇧🇩",
  },
  BGN: {
    symbol: "лв",
    name: "Bulgarian Lev",
    icon: "🇧🇬",
  },
  BHD: {
    symbol: ".د.ب",
    name: "Bahraini Dinar",
    icon: "🇧🇭",
  },
  BIF: {
    symbol: "FBu",
    name: "Burundian Franc",
    icon: "🇧🇮",
  },
  BMD: {
    symbol: "$",
    name: "Bermudian Dollar",
    icon: "🇧🇲",
  },
  BND: {
    symbol: "$",
    name: "Brunei Dollar",
    icon: "🇧🇳",
  },
  BOB: {
    symbol: "Bs.",
    name: "Bolivian Boliviano",
    icon: "🇧🇴",
  },
  BRL: {
    symbol: "R$",
    name: "Brazilian Real",
    icon: "🇧🇷",
  },
  BSD: {
    symbol: "$",
    name: "Bahamian Dollar",
    icon: "🇧🇸",
  },
  BTN: {
    symbol: "Nu",
    name: "Bhutanese Ngultrum",
    icon: "🇧🇹",
  },
  BWP: {
    symbol: "P",
    name: "Botswana Pula",
    icon: "🇧🇼",
  },
  BYN: {
    symbol: "Br",
    name: "Belarusian Ruble",
    icon: "🇧🇾",
  },
  BZD: {
    symbol: "$",
    name: "Belize Dollar",
    icon: "🇧🇿",
  },
  CAD: {
    symbol: "C$",
    name: "Canadian Dollar",
    icon: "🇨🇦",
  },
  CDF: {
    symbol: "FC",
    name: "Congolese Franc",
    icon: "🇨🇩",
  },
  CHF: {
    symbol: "Fr.",
    name: "Swiss Franc",
    icon: "🇨🇭",
  },
  CLP: {
    symbol: "$",
    name: "Chilean Peso",
    icon: "🇨🇱",
  },
  CNY: {
    symbol: "¥",
    name: "Chinese Yuan",
    icon: "🇨🇳",
  },
  COP: {
    symbol: "$",
    name: "Colombian Peso",
    icon: "🇨🇴",
  },
  CRC: {
    symbol: "₡",
    name: "Costa Rican Colón",
    icon: "🇨🇷",
  },
  CUP: {
    symbol: "$",
    name: "Cuban Peso",
    icon: "🇨🇺",
  },
  CVE: {
    symbol: "Esc",
    name: "Cape Verdean Escudo",
    icon: "🇨🇻",
  },
  CZK: {
    symbol: "Kč",
    name: "Czech Koruna",
    icon: "🇨🇿",
  },
  DJF: {
    symbol: "Fdj",
    name: "Djiboutian Franc",
    icon: "🇩🇯",
  },
  DKK: {
    symbol: "kr",
    name: "Danish Krone",
    icon: "🇬🇱",
  },
  DOP: {
    symbol: "$",
    name: "Dominican Peso",
    icon: "🇩🇴",
  },
  DZD: {
    symbol: "د.ج",
    name: "Algerian Dinar",
    icon: "🇩🇿",
  },
  EGP: {
    symbol: "£",
    name: "Egyptian Pound",
    icon: "🇪🇬",
  },
  ERN: {
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    icon: "🇪🇷",
  },
  ETB: {
    symbol: "Br",
    name: "Ethiopian Birr",
    icon: "🇪🇹",
  },
  EUR: {
    symbol: "€",
    name: "Euro",
    icon: "🇪🇺",
  },
  FJD: {
    symbol: "$",
    name: "Fijian Dollar",
    icon: "🇫🇯",
  },
  FKP: {
    symbol: "£",
    name: "Falkland Islands Pound",
    icon: "🇫🇰",
  },
  GBP: {
    symbol: "£",
    name: "British Pound Sterling",
    icon: "🇬🇧",
  },
  GEL: {
    symbol: "₾",
    name: "Georgian Lari",
    icon: "🇬🇪",
  },
  GHS: {
    symbol: "₵",
    name: "Ghanaian Cedi",
    icon: "🇬🇭",
  },
  GIP: {
    symbol: "£",
    name: "Gibraltar Pound",
    icon: "🇬🇮",
  },
  GMD: {
    symbol: "D",
    name: "Gambian Dalasi",
    icon: "🇬🇲",
  },
  GNF: {
    symbol: "FG",
    name: "Guinean Franc",
    icon: "🇬🇳",
  },
  GTQ: {
    symbol: "Q",
    name: "Guatemalan Quetzal",
    icon: "🇬🇹",
  },
  GYD: {
    symbol: "$",
    name: "Guyanese Dollar",
    icon: "🇬🇾",
  },
  HKD: {
    symbol: "$",
    name: "Hong Kong Dollar",
    icon: "🇭🇰",
  },
  HNL: {
    symbol: "L",
    name: "Honduran Lempira",
    icon: "🇭🇳",
  },
  HRK: {
    symbol: "kn",
    name: "Croatian Kuna",
    icon: "🇭🇷",
  },
  HTG: {
    symbol: "G",
    name: "Haitian Gourde",
    icon: "🇭🇹",
  },
  HUF: {
    symbol: "Ft",
    name: "Hungarian Forint",
    icon: "🇭🇺",
  },
  IDR: {
    symbol: "Rp",
    name: "Indonesian Rupiah",
    icon: "🇮🇩",
  },
  ILS: {
    symbol: "₪",
    name: "Israeli New Shekel",
    icon: "🇵🇸",
  },
  INR: {
    symbol: "₹",
    name: "Indian Rupee",
    icon: "🇮🇳",
  },
  IQD: {
    symbol: "ع.د",
    name: "Iraqi Dinar",
    icon: "🇮🇶",
  },
  IRR: {
    symbol: "﷼",
    name: "Iranian Rial",
    icon: "🇮🇷",
  },
  ISK: {
    symbol: "kr",
    name: "Icelandic Króna",
    icon: "🇮🇸",
  },
  JMD: {
    symbol: "$",
    name: "Jamaican Dollar",
    icon: "🇯🇲",
  },
  JOD: {
    symbol: "د.ا",
    name: "Jordanian Dinar",
    icon: "🇯🇴",
  },
  JPY: {
    symbol: "¥",
    name: "Japanese Yen",
    icon: "🇯🇵",
  },
  KES: {
    symbol: "KSh",
    name: "Kenyan Shilling",
    icon: "🇰🇪",
  },
  KGS: {
    symbol: "лв",
    name: "Kyrgyzstani Som",
    icon: "🇰🇬",
  },
  KHR: {
    symbol: "៛",
    name: "Cambodian Riel",
    icon: "🇰🇭",
  },
  KMF: {
    symbol: "CF",
    name: "Comorian Franc",
    icon: "🇰🇲",
  },
  KPW: {
    symbol: "₩",
    name: "North Korean Won",
    icon: "🇰🇵",
  },
  KRW: {
    symbol: "₩",
    name: "South Korean Won",
    icon: "🇰🇷",
  },
  KWD: {
    symbol: "د.ك",
    name: "Kuwaiti Dinar",
    icon: "🇰🇼",
  },
  KYD: {
    symbol: "$",
    name: "Cayman Islands Dollar",
    icon: "🇰🇾",
  },
  KZT: {
    symbol: "₸",
    name: "Kazakhstani Tenge",
    icon: "🇰🇿",
  },
  LAK: {
    symbol: "₭",
    name: "Lao Kip",
    icon: "🇱🇦",
  },
  LBP: {
    symbol: "ل.ل",
    name: "Lebanese Pound",
    icon: "🇱🇧",
  },
  LKR: {
    symbol: "₨",
    name: "Sri Lankan Rupee",
    icon: "🇱🇰",
  },
  LRD: {
    symbol: "$",
    name: "Liberian Dollar",
    icon: "🇱🇷",
  },
  LSL: {
    symbol: "L",
    name: "Lesotho Loti",
    icon: "🇱🇸",
  },
  LYD: {
    symbol: "ل.د",
    name: "Libyan Dinar",
    icon: "🇱🇾",
  },
  MAD: {
    symbol: "د.م.",
    name: "Moroccan Dirham",
    icon: "🇪🇭",
  },
  MDL: {
    symbol: "L",
    name: "Moldovan Leu",
    icon: "🇲🇩",
  },
  MGA: {
    symbol: "Ar",
    name: "Malagasy Ariary",
    icon: "🇲🇬",
  },
  MKD: {
    symbol: "ден",
    name: "Macedonian Denar",
    icon: "🇲🇰",
  },
  MMK: {
    symbol: "Ks",
    name: "Myanmar Kyat",
    icon: "🇲🇲",
  },
  MNT: {
    symbol: "₮",
    name: "Mongolian Tögrög",
    icon: "🇲🇳",
  },
  MOP: {
    symbol: "MOP$",
    name: "Macanese Pataca",
    icon: "🇲🇴",
  },
  MRU: {
    symbol: "UM",
    name: "Mauritanian Ouguiya",
    icon: "🇲🇷",
  },
  MUR: {
    symbol: "₨",
    name: "Mauritian Rupee",
    icon: "🇲🇺",
  },
  MVR: {
    symbol: "Rf",
    name: "Maldivian Rufiyaa",
    icon: "🇲🇻",
  },
  MWK: {
    symbol: "MK",
    name: "Malawian Kwacha",
    icon: "🇲🇼",
  },
  MXN: {
    symbol: "$",
    name: "Mexican Peso",
    icon: "🇲🇽",
  },
  MYR: {
    symbol: "RM",
    name: "Malaysian Ringgit",
    icon: "🇲🇾",
  },
  MZN: {
    symbol: "MT",
    name: "Mozambican Metical",
    icon: "🇲🇿",
  },
  "N/A": {
    symbol: "N/A",
    name: "N/A",
    icon: "🇦🇶",
  },
  NAD: {
    symbol: "$",
    name: "Namibian Dollar",
    icon: "🇳🇦",
  },
  NGN: {
    symbol: "₦",
    name: "Nigerian Naira",
    icon: "🇳🇬",
  },
  NIO: {
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    icon: "🇳🇮",
  },
  NOK: {
    symbol: "kr",
    name: "Norwegian Krone",
    icon: "🇸🇯",
  },
  NPR: {
    symbol: "₨",
    name: "Nepalese Rupee",
    icon: "🇳🇵",
  },
  NZD: {
    symbol: "$",
    name: "New Zealand Dollar",
    icon: "🇹🇰",
  },
  OMR: {
    symbol: "ر.ع.",
    name: "Omani Rial",
    icon: "🇴🇲",
  },
  PAB: {
    symbol: "B/.",
    name: "Panamanian Balboa",
    icon: "🇵🇦",
  },
  PEN: {
    symbol: "S/",
    name: "Peruvian Sol",
    icon: "🇵🇪",
  },
  PGK: {
    symbol: "K",
    name: "Papua New Guinean Kina",
    icon: "🇵🇬",
  },
  PHP: {
    symbol: "₱",
    name: "Philippine Peso",
    icon: "🇵🇭",
  },
  PKR: {
    symbol: "₨",
    name: "Pakistani Rupee",
    icon: "🇵🇰",
  },
  PLN: {
    symbol: "zł",
    name: "Polish Złoty",
    icon: "🇵🇱",
  },
  PYG: {
    symbol: "₲",
    name: "Paraguayan Guaraní",
    icon: "🇵🇾",
  },
  QAR: {
    symbol: "ر.ق",
    name: "Qatari Riyal",
    icon: "🇶🇦",
  },
  RON: {
    symbol: "lei",
    name: "Romanian Leu",
    icon: "🇷🇴",
  },
  RSD: {
    symbol: "дин.",
    name: "Serbian Dinar",
    icon: "🇷🇸",
  },
  RUB: {
    symbol: "₽",
    name: "Russian Ruble",
    icon: "🇷🇺",
  },
  RWF: {
    symbol: "FRw",
    name: "Rwandan Franc",
    icon: "🇷🇼",
  },
  SAR: {
    symbol: "ر.س",
    name: "Saudi Riyal",
    icon: "🇸🇦",
  },
  SBD: {
    symbol: "$",
    name: "Solomon Islands Dollar",
    icon: "🇸🇧",
  },
  SCR: {
    symbol: "₨",
    name: "Seychellois Rupee",
    icon: "🇸🇨",
  },
  SDG: {
    symbol: "ج.س.",
    name: "Sudanese Pound",
    icon: "🇸🇩",
  },
  SEK: {
    symbol: "kr",
    name: "Swedish Krona",
    icon: "🇸🇪",
  },
  SGD: {
    symbol: "S$",
    name: "Singapore Dollar",
    icon: "🇸🇬",
  },
  SHP: {
    symbol: "£",
    name: "Saint Helena Pound",
    icon: "🇸🇭",
  },
  SLE: {
    symbol: "Le",
    name: "Sierra Leonean Leone",
    icon: "🇸🇱",
  },
  SOS: {
    symbol: "Sh",
    name: "Somali Shilling",
    icon: "🇸🇴",
  },
  SRD: {
    symbol: "$",
    name: "Surinamese Dollar",
    icon: "🇸🇷",
  },
  SSP: {
    symbol: "£",
    name: "South Sudanese Pound",
    icon: "🇸🇸",
  },
  STN: {
    symbol: "Db",
    name: "Sao Tomean Dobra",
    icon: "🇸🇹",
  },
  SYP: {
    symbol: "£",
    name: "Syrian Pound",
    icon: "🇸🇾",
  },
  SZL: {
    symbol: "L",
    name: "Swazi Lilangeni",
    icon: "🇸🇿",
  },
  THB: {
    symbol: "฿",
    name: "Thai Baht",
    icon: "🇹🇭",
  },
  TJS: {
    symbol: "SM",
    name: "Tajikistani Somoni",
    icon: "🇹🇯",
  },
  TMT: {
    symbol: "m",
    name: "Turkmenistani Manat",
    icon: "🇹🇲",
  },
  TND: {
    symbol: "د.ت",
    name: "Tunisian Dinar",
    icon: "🇹🇳",
  },
  TOP: {
    symbol: "T$",
    name: "Tongan Paʻanga",
    icon: "🇹🇴",
  },
  TRY: {
    symbol: "₺",
    name: "Turkish Lira",
    icon: "🇹🇷",
  },
  TTD: {
    symbol: "$",
    name: "Trinidad and Tobago Dollar",
    icon: "🇹🇹",
  },
  TWD: {
    symbol: "$",
    name: "New Taiwan Dollar",
    icon: "🇹🇼",
  },
  TZS: {
    symbol: "TSh",
    name: "Tanzanian Shilling",
    icon: "🇹🇿",
  },
  UAH: {
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    icon: "🇺🇦",
  },
  UGX: {
    symbol: "USh",
    name: "Ugandan Shilling",
    icon: "🇺🇬",
  },
  USD: {
    symbol: "$",
    name: "US Dollar",
    icon: "🇺🇲",
  },
  UYU: {
    symbol: "$U",
    name: "Uruguayan Peso",
    icon: "🇺🇾",
  },
  UZS: {
    symbol: "so'm",
    name: "Uzbekistani Soʻm",
    icon: "🇺🇿",
  },
  VES: {
    symbol: "Bs.",
    name: "Venezuelan Bolívar",
    icon: "🇻🇪",
  },
  VND: {
    symbol: "₫",
    name: "Vietnamese Đồng",
    icon: "🇻🇳",
  },
  VUV: {
    symbol: "VT",
    name: "Vanuatu Vatu",
    icon: "🇻🇺",
  },
  WST: {
    symbol: "T",
    name: "Samoan Tala",
    icon: "🇼🇸",
  },
  XAF: {
    symbol: "CFA",
    name: "Central African CFA Franc",
    icon: "🇬🇦",
  },
  XCD: {
    symbol: "$",
    name: "Eastern Caribbean Dollar",
    icon: "🇻🇨",
  },
  XOF: {
    symbol: "CFA",
    name: "West African CFA Franc",
    icon: "🇹🇬",
  },
  XPF: {
    symbol: "₣",
    name: "CFP Franc",
    icon: "🇼🇫",
  },
  YER: {
    symbol: "﷼",
    name: "Yemeni Rial",
    icon: "🇾🇪",
  },
  ZAR: {
    symbol: "R",
    name: "South African Rand",
    icon: "🇿🇦",
  },
  ZMW: {
    symbol: "ZK",
    name: "Zambian Kwacha",
    icon: "🇿🇲",
  },
  ZWL: {
    symbol: "$",
    name: "Zimbabwean Dollar",
    icon: "🇿🇼",
  },
};

export const CURRENCY_SYMBOLS: string[] = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHF",
  "CLP",
  "CNY",
  "COP",
  "CRC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HRK",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "MZN",
  "N/A",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLE",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "UYU",
  "UZS",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XOF",
  "XPF",
  "YER",
  "ZAR",
  "ZMW",
  "ZWL",
];
