name: CI (test suite)

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      HUSKY: 0

    strategy:
      matrix:
        task: [audit, lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.task }}
        run: |
          if [ "${{ matrix.task }}" == "audit" ]; then
            pnpm audit
          elif [ "${{ matrix.task }}" == "lint" ]; then
            pnpm lint:ci
          elif [ "${{ matrix.task }}" == "test" ]; then
            pnpm test
          fi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5
        if: ${{ matrix.task }} == "test"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: still-forest/exchange-house-mobile
