name: Publish to GHCR

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build image for scanning
        run: docker build -t temp-image-for-scan .

      - name: Run Trivy vulnerability scanner in table format first
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: "temp-image-for-scan"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          format: "table" # Use table format for human readability

      - name: Run Trivy vulnerability scanner in SARIF format
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: "temp-image-for-scan"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
        with:
          driver: docker-container
          # This explicitly sets the driver to use containers instead of the default Docker driver

      - name: Build and push server image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/exchange-house:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/exchange-house:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/exchange-house:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/exchange-house:buildcache,mode=max
