name: Firebase CI (lint)

on:
  pull_request:
    branches:
      - main
    paths:
      - "firebase/functions/**"

defaults:
  run:
    working-directory: ./firebase/functions

jobs:
  test-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        include:
          - task: lint
            run_command: pnpm lint:ci
          - task: build
            run_command: pnpm build

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.10.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.task }}
        run: ${{ matrix.run_command }}
